// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package tenantstore

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type StorageBucket struct {
	ID               string
	Name             string
	ProjectID        string
	AccessLevel      string
	FileSizeLimit    *int64
	AllowedMimeTypes []string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type StorageObject struct {
	ID        uuid.UUID
	BucketID  string
	Name      string
	Owner     pgtype.UUID
	Size      *int64
	MimeType  *string
	Etag      *string
	Metadata  []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}
