// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package tenantstore

import (
	"context"
)

type Querier interface {
	CountObjectsByBucketID(ctx context.Context, bucketID string) (int64, error)
	CreateBucket(ctx context.Context, arg CreateBucketParams) (StorageBucket, error)
	CreateObject(ctx context.Context, arg CreateObjectParams) (StorageObject, error)
	DeleteBucket(ctx context.Context, arg DeleteBucketParams) (StorageBucket, error)
	DeleteObject(ctx context.Context, arg DeleteObjectParams) error
	GetBucketByID(ctx context.Context, arg GetBucketByIDParams) (StorageBucket, error)
	GetBucketByName(ctx context.Context, arg GetBucketByNameParams) (StorageBucket, error)
	GetObjectByBucketAndName(ctx context.Context, arg GetObjectByBucketAndNameParams) (StorageObject, error)
	ListBuckets(ctx context.Context, arg ListBucketsParams) ([]StorageBucket, error)
	ListObjectsByBucket(ctx context.Context, arg ListObjectsByBucketParams) ([]StorageObject, error)
	UpdateBucket(ctx context.Context, arg UpdateBucketParams) (StorageBucket, error)
	UpsertObject(ctx context.Context, arg UpsertObjectParams) (StorageObject, error)
}

var _ Querier = (*Queries)(nil)
