// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package tenantstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countObjectsByBucketID = `-- name: CountObjectsByBucketID :one
SELECT count(*) FROM storage.objects WHERE bucket_id = $1
`

func (q *Queries) CountObjectsByBucketID(ctx context.Context, bucketID string) (int64, error) {
	row := q.db.QueryRow(ctx, countObjectsByBucketID, bucketID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBucket = `-- name: CreateBucket :one
INSERT INTO storage.buckets (id, name, project_id, access_level, file_size_limit, allowed_mime_types)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, project_id, access_level, file_size_limit, allowed_mime_types, created_at, updated_at
`

type CreateBucketParams struct {
	ID               string
	Name             string
	ProjectID        string
	AccessLevel      string
	FileSizeLimit    *int64
	AllowedMimeTypes []string
}

func (q *Queries) CreateBucket(ctx context.Context, arg CreateBucketParams) (StorageBucket, error) {
	row := q.db.QueryRow(ctx, createBucket,
		arg.ID,
		arg.Name,
		arg.ProjectID,
		arg.AccessLevel,
		arg.FileSizeLimit,
		arg.AllowedMimeTypes,
	)
	var i StorageBucket
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.AccessLevel,
		&i.FileSizeLimit,
		&i.AllowedMimeTypes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createObject = `-- name: CreateObject :one
INSERT INTO storage.objects (bucket_id, name, owner, size, mime_type, etag, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, bucket_id, name, owner, size, mime_type, etag, metadata, created_at, updated_at
`

type CreateObjectParams struct {
	BucketID string
	Name     string
	Owner    pgtype.UUID
	Size     *int64
	MimeType *string
	Etag     *string
	Metadata []byte
}

func (q *Queries) CreateObject(ctx context.Context, arg CreateObjectParams) (StorageObject, error) {
	row := q.db.QueryRow(ctx, createObject,
		arg.BucketID,
		arg.Name,
		arg.Owner,
		arg.Size,
		arg.MimeType,
		arg.Etag,
		arg.Metadata,
	)
	var i StorageObject
	err := row.Scan(
		&i.ID,
		&i.BucketID,
		&i.Name,
		&i.Owner,
		&i.Size,
		&i.MimeType,
		&i.Etag,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBucket = `-- name: DeleteBucket :one
DELETE FROM storage.buckets WHERE id = $1 AND project_id = $2 RETURNING id, name, project_id, access_level, file_size_limit, allowed_mime_types, created_at, updated_at
`

type DeleteBucketParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) DeleteBucket(ctx context.Context, arg DeleteBucketParams) (StorageBucket, error) {
	row := q.db.QueryRow(ctx, deleteBucket, arg.ID, arg.ProjectID)
	var i StorageBucket
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.AccessLevel,
		&i.FileSizeLimit,
		&i.AllowedMimeTypes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteObject = `-- name: DeleteObject :exec
DELETE FROM storage.objects WHERE bucket_id = $1 AND name = $2
`

type DeleteObjectParams struct {
	BucketID string
	Name     string
}

func (q *Queries) DeleteObject(ctx context.Context, arg DeleteObjectParams) error {
	_, err := q.db.Exec(ctx, deleteObject, arg.BucketID, arg.Name)
	return err
}

const getBucketByID = `-- name: GetBucketByID :one
SELECT id, name, project_id, access_level, file_size_limit, allowed_mime_types, created_at, updated_at FROM storage.buckets WHERE id = $1 AND project_id = $2
`

type GetBucketByIDParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) GetBucketByID(ctx context.Context, arg GetBucketByIDParams) (StorageBucket, error) {
	row := q.db.QueryRow(ctx, getBucketByID, arg.ID, arg.ProjectID)
	var i StorageBucket
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.AccessLevel,
		&i.FileSizeLimit,
		&i.AllowedMimeTypes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBucketByName = `-- name: GetBucketByName :one
SELECT id, name, project_id, access_level, file_size_limit, allowed_mime_types, created_at, updated_at FROM storage.buckets WHERE name = $1 AND project_id = $2
`

type GetBucketByNameParams struct {
	Name      string
	ProjectID string
}

func (q *Queries) GetBucketByName(ctx context.Context, arg GetBucketByNameParams) (StorageBucket, error) {
	row := q.db.QueryRow(ctx, getBucketByName, arg.Name, arg.ProjectID)
	var i StorageBucket
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.AccessLevel,
		&i.FileSizeLimit,
		&i.AllowedMimeTypes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getObjectByBucketAndName = `-- name: GetObjectByBucketAndName :one
SELECT id, bucket_id, name, owner, size, mime_type, etag, metadata, created_at, updated_at FROM storage.objects WHERE bucket_id = $1 AND name = $2
`

type GetObjectByBucketAndNameParams struct {
	BucketID string
	Name     string
}

func (q *Queries) GetObjectByBucketAndName(ctx context.Context, arg GetObjectByBucketAndNameParams) (StorageObject, error) {
	row := q.db.QueryRow(ctx, getObjectByBucketAndName, arg.BucketID, arg.Name)
	var i StorageObject
	err := row.Scan(
		&i.ID,
		&i.BucketID,
		&i.Name,
		&i.Owner,
		&i.Size,
		&i.MimeType,
		&i.Etag,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBuckets = `-- name: ListBuckets :many
SELECT id, name, project_id, access_level, file_size_limit, allowed_mime_types, created_at, updated_at FROM storage.buckets
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBucketsParams struct {
	ProjectID string
	Limit     int32
	Offset    int32
}

func (q *Queries) ListBuckets(ctx context.Context, arg ListBucketsParams) ([]StorageBucket, error) {
	rows, err := q.db.Query(ctx, listBuckets, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StorageBucket
	for rows.Next() {
		var i StorageBucket
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProjectID,
			&i.AccessLevel,
			&i.FileSizeLimit,
			&i.AllowedMimeTypes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObjectsByBucket = `-- name: ListObjectsByBucket :many
SELECT id, bucket_id, name, owner, size, mime_type, etag, metadata, created_at, updated_at FROM storage.objects
WHERE bucket_id = $1
ORDER BY name
LIMIT $2 OFFSET $3
`

type ListObjectsByBucketParams struct {
	BucketID string
	Limit    int32
	Offset   int32
}

func (q *Queries) ListObjectsByBucket(ctx context.Context, arg ListObjectsByBucketParams) ([]StorageObject, error) {
	rows, err := q.db.Query(ctx, listObjectsByBucket, arg.BucketID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StorageObject
	for rows.Next() {
		var i StorageObject
		if err := rows.Scan(
			&i.ID,
			&i.BucketID,
			&i.Name,
			&i.Owner,
			&i.Size,
			&i.MimeType,
			&i.Etag,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBucket = `-- name: UpdateBucket :one
UPDATE storage.buckets
SET access_level = COALESCE($3, access_level),
    file_size_limit = COALESCE($4, file_size_limit),
    allowed_mime_types = COALESCE($5, allowed_mime_types),
    updated_at = now()
WHERE id = $1 AND project_id = $2
RETURNING id, name, project_id, access_level, file_size_limit, allowed_mime_types, created_at, updated_at
`

type UpdateBucketParams struct {
	ID               string
	ProjectID        string
	AccessLevel      *string
	FileSizeLimit    *int64
	AllowedMimeTypes []string
}

func (q *Queries) UpdateBucket(ctx context.Context, arg UpdateBucketParams) (StorageBucket, error) {
	row := q.db.QueryRow(ctx, updateBucket,
		arg.ID,
		arg.ProjectID,
		arg.AccessLevel,
		arg.FileSizeLimit,
		arg.AllowedMimeTypes,
	)
	var i StorageBucket
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.AccessLevel,
		&i.FileSizeLimit,
		&i.AllowedMimeTypes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertObject = `-- name: UpsertObject :one
INSERT INTO storage.objects (bucket_id, name, owner, size, mime_type, etag, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (bucket_id, name) DO UPDATE
SET size = EXCLUDED.size, mime_type = EXCLUDED.mime_type, etag = EXCLUDED.etag,
    metadata = EXCLUDED.metadata, owner = EXCLUDED.owner, updated_at = now()
RETURNING id, bucket_id, name, owner, size, mime_type, etag, metadata, created_at, updated_at
`

type UpsertObjectParams struct {
	BucketID string
	Name     string
	Owner    pgtype.UUID
	Size     *int64
	MimeType *string
	Etag     *string
	Metadata []byte
}

func (q *Queries) UpsertObject(ctx context.Context, arg UpsertObjectParams) (StorageObject, error) {
	row := q.db.QueryRow(ctx, upsertObject,
		arg.BucketID,
		arg.Name,
		arg.Owner,
		arg.Size,
		arg.MimeType,
		arg.Etag,
		arg.Metadata,
	)
	var i StorageObject
	err := row.Scan(
		&i.ID,
		&i.BucketID,
		&i.Name,
		&i.Owner,
		&i.Size,
		&i.MimeType,
		&i.Etag,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
