---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCNQuxoYA7XVbSh2WJjwrOuJVB0Z3td+moLuw8emKlIwWRDRl2g+aC/eZj5zn2DKjQbKvgn+CjKSisbuRjiv26jfNnZucvm7wCeGMy5OELJ8xZF1v2lrg9XdZ802xozTyVjPWWTRdO2TIToG91nG+1+/nWgLlKvifSlsNqv/8ak2uUX5jcl6LF91LK84HlNUc1IaSxHMWv5jrT2PRhwGJws8r7Qo7o7pSib/baWGbyFmISm85Y8euQL8wGj2ddWd/AjcJTRliaibL3SqerEJNTkZSvNFcT4DcIs4xpxKGvooxrj7GhNVIS5i0I9fXH9lMg4hLzaG9pO7ZBgZEWl3v9Do+BE8H7xFB8CbCtfXVRbHo38dfcpm6XCn2OgdHuw1lwMeYIRd5BYOzwgfc24Zy3NVtVOTHTE+GbUOl2USCvUJzecXiCMzlZcVqj/TQHTKoOTyox9gAVgvw08Ez1N/KA0SkDy/N3wrJga+Xu3zr5/Lovx/TORFwqJXyr7rFI4RM2Z2XP84Zd77rSnunvlgyA7Ok+R1bi7HJHQtZMBBXT0JP1z2Q4+bpPhjiBOpnv264xmsaceZT3WuiWsVCBMI55Le/GbStPgx72jXNIO4eNX+Yqvno5u9V/OEgmswliISWzSpA5b1sJpq+hhPZjhoNI4wwojQ8rjtvNjZeLO6kvDNdS6Ra9JH8dLzbPTVua1Jl0AWo/JU1MdNCqI7BOYB6Z8qzpxgnvAsEJ125gffVccriExof2UrgVkSnd1E840RNcjvRtVEA==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
