---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCmWtXuTdS88/7Y76qXVxG6/NLIJFOsaO1XCG03cKeqL8YZ3Y3H3twq8MiYV3qCWSzb0Ts3nEsy2nQW8Pl2qQt2LQATPrzRn6A+bNMT79gGJCB8ZEqMDCD5/XKHsDMeW+MV53aBH58Sc12n78GVzozSWvQ1Ik/E13JYqXmB4C9TEJ6IXKlL3aKh0LV6u3DJIrj+jSzFmaf3Ea0LpvAnwrw2P13mgHh9R3mNvPfA1jOtcO5xmR3gF+saFy7oKdtMtUMttBzmaEJ7N+shQzaYLndACuQQQn/7i5fn1hWi7Nf9QsCvteCheG98uueb4ogtODsFM2gASS+xLxIZ8poeMvJLxU6XBxFO1SjXBf/SYlNqNRca8/SCfNqqYDy2nh65I27hYpynH2m6e7XEgqmGL9UQfutPRQhUeCaCEvM9pnA1mmdxEoyyDdH+GaGnPcth2Cs8+eufio6rm96X7dftYQfaGtRlj1lzjqpEFTO9d1ymiEctaE7Mnc7ebEiraBmqp4q1LGnmk+oV+gA4JM7nWExHlwoUz0yAMOm/a2kLeB6uDFm9CYh8IVMdQ8x/EoKKH9yy+c0t0Osu8VPNnv8R6PTUVfNtA3kQ3NFx5Oew7Kf8OfGltxi6j0/tlL3GbJA2dHHBk2PGnLwfTEbBH5w6i+YWv3A4uDUHiaHEnMdcmhiQEGsR4J0pvFywYg/ypRkaTH5jWYkQCZoxuQnn+vL25yVCszCYKT/hKPfEYC9ODhSbF3Aw0iyILB8cxdDIjS3o70qzpvKH/Q==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
