---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-webhook
  namespace: monitoring
spec:
  encryptedData:
    url: AgB/ivh+rOcoH3mJaSCV1yzcUd7vlEHr/qVpzxcpruYndnl1Mron6XvP1qr+e87nT7fquYcVI6PGgw9yoNcY47lBPCUANzq6ScsutXwy67T4CPpTBi12QjR95R760Qyli/4k34/8QHez+Dtb6tII4cCdrbcMhRiSXj3SY/cPfdzr4AXWnChaA28FNvHe7w8AQSioeX7mX3pmduUaI5E3J89sR2KnF4zIJf9oJdvx1YLDt6fnOJ/3wPmuglhA9sqO9S7Jd6bsPGJjiiuf+U3kkWAFHMvNumTWNDRmiqKxlvmqInVv6BWJb7YK5xtCGCMZvE4AvuAbURD9hIAHOW1+7a6FdBObcyhEARYXo8mkozWraNdjd3ygkod5wnEgZPURxlTRXRLvTpV7pEx6x+AZNrYPA3NVBeHLP1VNCtXUlJT7bI5unXaTNcFTMuuVOJ8A63Z9gyeI7hIKsnUKXA74IfLIsYn61wQpswco+NDg3G7Jc8FkM0acvw6UxmG6Oo1eiBwWXnkTI5wwy/JyB26Wu7248MS7Jo6CiHUQT8pI0UzPSML0pkQDomFtbZlaJKCGbfJqaGgPGosokuoEl0hJSvmMA6mXR2o1YA9CEeCUD3TC7GFTTx1xxSDrWaL/H7SJqyfGtpbm7opmFdGa0NsbhDg+Ds5/E4Fz/OZbDB6fORumPuQPc8qTCivvZYHi8LhZiWGy
  template:
    metadata:
      creationTimestamp: null
      name: discord-webhook
      namespace: monitoring
