---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: platform-system
spec:
  encryptedData:
    .dockerconfigjson: AgApJW3HJrZ/SjOBL55hqMiRuaXavekXAL/an9Rloiu2Jy8zgx12DdQMOM7cys8f0JdBzS6evOQK1gj2rnMvmJbaGF7N9SFJ4EnFj9ryYJKsm2DK7a+vnSH1Hc1viLD23t/k1nitCN1Ar1OQXdozzeja3hKKqUMFtSABSJ6tZBCn3D4wlc6DfPDxTHyyqFNJOWLEgmEHNLAXLEKHlxvVx+rkB9Z3cTp+pZ39yoqhoP1ZAWg+0FDmG0j8q34ZabWJcGk/kZx0+C1kDh/sHC5nNkQ6BsuSWpOK8A2TlFi1gNjuX3j2C1V2gj7GjQM7Byr9nOC1GdM3+aErFKSavjHOBu/FJ/8qeLAJAnvcS94m4pEGyUr1mFMKoWlhvkj/m+tG2+QtSVPLjDAq/nEvvMfl/iRekHR2T8ge61Mm6zmkp3ZgZfysx/8OzzMGhEbZ3nOMZRB4HpzGY0pYmSEw1QXkOOKMF8+0lhSzETHfgravszSMFKB1O/3vBjq8RthEAcdoeSYr2nFkYbNryrrr3/CVfzaVCIX/9a0RVJrRrg48/gVnyszPZs1/s9UFguK9GEVQ0xy1cjc/tv7iwyJIGnKAJ0gOeFOtoUq/By31hT/qFxO/yk94KhuL610gLCiFlC1UCRwGCgwpnPn87hS6HYJPh0uOlzS9uCcTUdToFDmGSItxIc1Wc9mPg98rBEP8v64E0d+T7qLr3WZqNeXJMkfLWFHej817vMq/T8A22lkWU8OIIg8IjNwNd1HEANW65Va0zgbUpewYOG8WQSrNBNj4pf03CWFp0ODxO0GjmEIBeosN+rwcCQsHKPLmXUcGGNnK0nFI6nxbpfrsG7ozvrsPQnqhanaPhmbo3tJUQrv2O97oDW+s4zoFWO3sGfAo+YDSlZYOsJ1wCpi0sJJHLM1hE4jJ8LyCU+D6WhDUcDqU7veg7g0jMQ==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: platform-system
    type: kubernetes.io/dockerconfigjson
