---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: platform-system
spec:
  encryptedData:
    .dockerconfigjson: AgBns2v3wTfKoW/qnHZShaE2fU2ukL+ZjC5eVeWMWeskz08FXV+GOqQ6aUm2n/HLyokfQnYkF1C/kw0/PyJtgZrl4eszZqOXh8E4H1QKEam2Xz+iGmhg+P5UQc1qdal0/DubQ9oMa96d7FonTQOiw3QY3r5A8VgOZKgGSOs7oCdP4oKlJ+7XgvBG5WnkxcRBqHVvPTXr9yBNaoDL0+781eVBiCROM01NKncgu+OQn5VJVZdRhHWzV2QZgUjYGpsLKUNCQUjax5D1FCyBHYRf3AVHBKmCR7YH2eNvSMqlPee1rsa4WxLDOc93FIt1sxLJqvQrwbsKCFWn5yuSuWZip/i/J7F3/+xfch4p18AxWQZSL5POeFhaRTIlyd9FMOWCe+hjN8qzCrvWljjXS5JAOwvi2u6rH+YCG+4E0oqkOrH3AR0vpLe20Uc16bflcj9zVUuJ8aJTKMPOfnn9iwyEMWgRBO+Xk/nnKmAyZkexpDY42H3uIVYmRdEPjKa/CBCc/usUfTVZiPGbbaiEMFhwJ1+ONOH0Q3rARykRNfi/1MbycbKNIiHD7/q+d/11NoTYkaO7BoeJybcKCq3zPgVZIQmWSNTBgF6W4sb9Z+74JgXznWA1PZJ0qW5wWL9UZJXP0vi1atp9v+jHti9KF+sxz/63vvIab3wb9n9Lx/H7t4jHptBm/oYPC+R+ylF1xSWcUgGEEKvZflH0b00TA3BWwLODtt120LFgfwh4UUyxKwZ92RQ4v3dLxWpRS6P+3Tvgl8S3hsgiPXUDEhm0F4zgSWBwejIKWwNTCzy35OphB/C1gZVmBa1IZ6wmFHXPqwQOtIi7rwIxxK53xw2p1AIsxd8hEpGFXnYvlEBrcsrSCfX4bypb/tD6jLatrQbD6j1RYMQZqwL+wTwWazV8XB6L4ksGiM47vYX29dXatPKeYEr7zwY=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: platform-system
    type: kubernetes.io/dockerconfigjson
