---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: platform-system
spec:
  encryptedData:
    .dockerconfigjson: AgDAzYXaqrXwQ17zDf4mIN09D6l86hgTcbX6CfMytu4l/QJv0OkroVEz/C82Km+NmYm8Uh2IvIyctq2DMVlLBTTaawRPqYJ8dYWSgCpdRLe5PkFKbJcHw0w+c1V7Cvky1AsH8IAG/gErEGlYoCNT2PYqFwaorMH3EEUEtuZBtAAvs8P/13p43FXLNI/gGOd55qmUKTTPcJ2rh33ZUvYX89JjyaWTsMC7goZMm7AxX3HpiYudc9JH8vAaDnxhtphgP87ayQQbLt3MqnyQQCL5AgiD5vXTWBkph8+tZjndgXgpy9ydB+Uj9wfYQyNsNGvn7Huf1gL60188cvHqL8LPC4egIy/HEPYK0pLWS1WTDw7jFUp1EPuLSojmu/+5qZG2N4KoSJVfNkF2tX3u7+Nu4aOeg7kb1+wMscP0OO64c7oEgAEcsKq7p7d1782ysabJa9TlRLf0hqKId4ogpayOeTTg3AhmtpSTp+NEIE1TROmJnUmB3AEhzK7FxYfcLLFD6gX+plqlPWTmw8/tIoYrHhEU7O1LzX4GZOvSO9JHrOLlh1FkpmTfRPIgjfnVb7jJWvaWVVvm6NM70A6EU1vWHKI3wkB+Q1pAwA/VwDlzwRyFp+Bfoe/2CtE4bwxagIRcYEbTqGxsrWlnZKdIpi4q09UhVFxjplcYxez/nxNxem8PDN4TAtDXMe/IiHRxCtvPklrtjuxXUNCAHOpb2RwiGKPYdXb6GbYurPa/A6rVD3IED9SdHnw6i9LhdM0L/VFsdONkO+Cc6M81/wAzlFts+1Q56ekBQefotG6YTDKOY6Bw5y0bQgv+jpsYbvnr9SF3NCBv0Sb9vuYNk9iQXEaMjCtUgNKQXez9UrCdRMsNDHM/d88lLx+UiJxHr7cjBGVzyG25QQSe6EPFF4LKIiZCs1N6uAnSNPg6iUtRx7896eCWgAM=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: platform-system
    type: kubernetes.io/dockerconfigjson
