---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: platform-secrets
  namespace: platform-system
spec:
  encryptedData:
    DATABASE_URL: AgC8rxFZcy5mpULtZtxyzR2xSOhOZn6E2JX3h3dd2ISyXwPF+6BJgQfVj4Cw2KW67j9teC1uyiiHVS1OWYKJxdthoByn6vh1GYi9LkJQpVb8Mi/MbF8or0/hEmwh2QOXEvKcnGzpnK1EtQreJk62ZghH+gdWNC/eWg7UrJo938PTuLBcyxgckucj4HXa90Ad1R0IvjsT3wEHaPYnpRnMc3NIjqdU8pEHJ08dm6gItnDtEWccGQikByzTJ7cs9UM8XctPodKQgDdRCOfUQfS8mSJm+rXHHY6O9kuD3xBmhuc0cXLQtifQ1S061qn4BMazPoxkJ0x52Gk0JnhbS+zjwqoyZaY2HBge72XYpFgKkakU3K122/dKOXdHi9kKxfmER3V7dS0OSwaeCHRT8dtC0/FczFXiD4vQLy1SXc7FHOxA8lu+HV1c5zGP6sp5LFqV4C0Rf8WvbbkGV0eLati/bEfd0hVqJYZNJooknA99f5R5+CH0kPsYPROj+1QdTlzbXnlDfR7n7ITlMeOghDtDsLlwp1Op/vPAKyfgOIS2z+ORTyPMsHU31+g/K3vAW87z99Cl59gcVw0/z1NxVhrujQ5R6s49DYiDL2zK2QE15DMb5MtqqEpvLHUaF5zQT1zHUrHyNpS7bFvbJRLpym8uWinz0L3gOB39afBEIhetS3vG6cekqubAKPQhbWCzGZj72JY=
    JWT_SECRET: AgBqNqbH6yFrrQjVlOBbB6iAlmJuIEezEmvlTv02zoUfC1GCj/aBxqwCa/KpNrr4bez6JYjT7CQDeRuuEtr0M62dQp/FUVssbEDj27nmqxyLo2bqLt6gyVFlFLSir9qCex8d3nppXDwbJFo6zXGu6jZrQNbGEzE/CeaPtzutGZy7RXTuBZsnrHpXSjy2AyuMg6mhlvos25KXWWZBPIOXAzm52J9vHtnVYw+tjaYU0ytZQOpcXi8u0pAwJyQy24RgOjuBCQjbp+lQnmOzQGGjOM9JfW4kRaYIgvsBCAScHmkoBm8lxtW9RV3YMHYFb7PzXBwcK9qXZLgMqpmyo7UoaXOibSsMRGKCShO1QwND20YPVGVdRXw64FM/SFWbDmYDLJRrIoNLmY4n5JORJ69FkTeA8eyVuR4sZrZ+Ol4LNT05ot5P7b+5lV8Nis/tgMFD4oxeuuMYlgWnUNgSEKAqC77+Q6iY2kh8Obw6xB+fnhGacmhSAqyvMjPB0N266adtAShXLdc1/0IOQtXt1dbe0padGfKX643GSdzpuIByyJX/qOmzezzU6YrOm2fFlYYne+cqeIXqTXc96s9/3Ti+NxC1rvm6Qcv+4n/gucWYjrn/gN8c9wg3bV8t0F9Xw1cjji3YAcTvagPnwYZq0iSTRs2T62kvS9o5ivumymeMyNCwP7ps45PPRHM7arW+FSZHzVxnjH3koRzoHkPqSCIq3Mvz/3Bx/j8vY+tkmGic8DVzMQ+sgrcAjXFx9Yppx/B9QZC25ZRoheIW6uKYvsf8qbTX
  template:
    metadata:
      creationTimestamp: null
      name: platform-secrets
      namespace: platform-system
