---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: platform-secrets
  namespace: platform-system
spec:
  encryptedData:
    JWT_SECRET: AgAKsmeQdShV/VIY7t2R/QN+2ukPTeuEf2nCyoB96+JPHlR/Xpk1iv1UGJvrqKCPeyx/chliVLh9+ak2m6YY0yJwcP03s+fMmfPv28+tzRNqJHCtTv6yQD4excyfumjmPb8LcTrDOnHUtmbgAcvcYb/ZWv86t0/HP/aortOu27Si6I5kOUq7V8GBIaEXjIHvCpv6P0QYbVC+5F/SmBwfrFat58NFGdcEf/lQbJ1F1wLCER/t3qNvXsAIlEFHrz4FqsaB+cmMxhfhc6sQWe74u8SlaUBTZ22jdCVdEfJwOuTS5i/YJwV0yZJKmViAUz3LrUUTIsYJueyZsq9VWjzzeWuYt7OTSkhRHDAvEt5jpalGdf9ZppZaWZPZovgj9mginPqhZGL3Dr45y+PYPs4X/c4xpGqbqvRYs/PepYmeAuEe18pSHWtWI4zXOno7LSTRZNyfnc8qVGPOrRH73o6gFkzdqhuPcA0z+Kin2WnRcLzuc853AapZYXs6CcYIN4yho7/NFA97AzWdxQcO0csOoUjkmR0JDXf2+DGQyj4RSo1FGcx4r8b+VxL2Z6M2aRC/xG7O+cxj+xoekSprPxZnc3FHshDPP48PcpadkZsj9+vCJ1x8q49V4Q812d7/Ew4Zrhd5gPtBgZwHEwcgDaiu3Yy+BfZ7GSyMiDUok7jjPVlqbpFIyFg1HQsSMbq+So7pHuzht2FE/3PvVk0MquNw8JAfKGFbmdPngEtC9DzOuVIDMFBtCMyRcwAJJlCiNhZSd4e+ZQ2Y4FdoMWUnZgAAq8uc
  template:
    metadata:
      creationTimestamp: null
      name: platform-secrets
      namespace: platform-system
