---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: r2-backup-creds
  namespace: platform-system
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBDeW6ZZvjyqIl5MB6ZylUpZqFY/JrniDGlIWlHp+hA8I+rpw2nqLq0l6opuht0JHYB+EkRqdT+uNUyhoP9FI7qP3BGvHH63/1vFYJAC8rLAYHDkqp5T3LBfp30uKmb4BmSiI36Ku4se9+erH+Q6nDBljNp9yyqogij4chRb3aZWc7SFuOAP7njLx18FGB4lB81T4pOOjpY7pMzm34H6XwG+tZH6mt9htu3c+Ymk5abRYY3aGHKOSd5rWVACbvXJKgZWbp0hsa4fB6RCTUuBNODQ1bHxIKvXaXHbhAUurKtXVyMKLyihituEA840xFXNBSCMZb7ZTai2MXk1yW0fJ6hRDPZbUCczVcsCgxaZolmboeHo8ByNb2fs8xfOmvyBGs72cFOrud3P2CM3eT7eQIh2CQrZ6zSIhbFgk6qSHFnVuZcEggVKJE4sB5EFRqIjY3xr4YdtzAlmvLwzxIil1ivyFfARI2nlT9mHe4PTVrqxi+8yqcKGDcyd3se2XeuobMQ9wNUHtzrimkUR4fhGHpY0A4PY8F3P1ph+k05RSjC7Ps1b6Pv0ReUPgCbEZAopTJDgrj5hmkXtahTsQTj78heIKFcgnj8UUnL3DO4SBEyGSzrY2Td2LVe9Xp6/BEreMj8bjpe4X6dPqdO/yNHreH3Z9XODbyVXVm23Zm1FhnAJwVrtzNUGJwWT7ceS/zOWK0NvDaFeNHd9MOshCY+zWkL7BnEI7Vr0Sa0QUgyUrPRgQ==
    SECRET_ACCESS_KEY: AgCKkH+rPP5ucWkQQu9X9n4TWU5i8kHI8OWfrR2ko5iHmXXxI8CeATNMxp+SbXQhBIu5TW7WTXgw65IKXKjVbMhaGIRoe7KSwRWgxrUFeb18oSeHSJiNGMFXndruEBhXBJTazzuvn6mycqhxWNWnxbBjMtJrMEDIzQquK2qAAqKnEF05BoFLjOEeva05Oolk4qrpW4F3NNayOJK5h2hO521qGLzbcBcdeAt8vibzqTCXhfjRNa4eIlHpq6PjJfTYUwRcp8XlpEF+TnbXwqRrqjoRXVJQog6vjk2f8RU+x9kX/nnMJBZxb8ChJt4Fua15lXkJXzKqcZ4QCMeaDUqikZjZE8Fswkqf4J05oW2GChrVnSrt1R0PtdHAvhuM4JTSR/IOu43EPo1cypardtVXsJHhGxLLmQf3LSmxNcZMyOGAa12ahbNgQjyqc/Qm+AEKLaP/ZbjWK+kPFaFH02b6oOABcroNAh/JEZgIMj3ASOxeJs60peM6t/WmMhSB4SDAsryKRmYgYIRBKmdGRcHstmigjJxMiMcSgLRTQlLXML6ejhUWhHzH2gAig5oqoI2sAwJIEup97yyAVkXSXp7EaAHWe3JlOxfs4mkNYBA20cM4km6dOVY/ts50WHDTAPxY4w6y32uLFw2sN25LlI6Dwz/t7mkTrCeRqJeCnwXpQ2Zul0t+xg3woIC/3Y4iJQr8k9FtboYaP715gxPenf1iwqeA1MaPM4uQfO6JXa0KnVaIM2+7RgrFkjLfZ2NOYT3O1KmO0iXxLnhLR+n4lEeTWHXN
  template:
    metadata:
      creationTimestamp: null
      name: r2-backup-creds
      namespace: platform-system
