---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: r2-backup-creds
  namespace: platform-system
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAd+Dce7ovCkqD6KB4IofXuXvk/GuaQ7xGE1u2iTbzNMxgy26vZ6o+WAd2ladzOU2uK+N6NRPEKiusr9/el04wd55ck9l0r9xw4qpLAbDHZi4YlltXSevHXmZ7ypxxxqAjj5J/B2wAvCfSUn/iahzN36PVBooAXOCP/dzUinKtdVqToumP+Mw2q0V/i8q1c200gqia0EHpEFX3MdVX1NUA/Uzap2WG6uHDLN433A4nWX0nMWx41VO3dALRjnBSDBdXBQNm/TLvZS9GvKskyddVFS0RwjpVIygAJXnJNXYrYs3zjd4dq4DiA0AhLJqSDSf4GDUu22brgCu6AGjQwShux8wLfTVEJWi1fKRAKZvxvXXGZSURiQnUjzTlAlgnVTmNOXLVvHncfG0P4FAU9YRsNU/eiU48rBBlYxkIHP/raxfZOaPGYwPn/82A7QuHg98GnSPKg3d+HytnMMZ8fbt9PlC2sEi9HSUtFjQ/82vqq2wWSIoG6GRcmJG6oJrZAYsZ/yLW170N4sJOK3ptt2Xlia5kSO+HySQIDq6OQ+MP3arHZUdf41H2DalvB+8vXfBCPBFNVchyNTxiUs/2SKZvccWm5AHmd4gBzdT8/9AMK90WJxgnXlA6pSuecoAT3ZFlTrDVvXwJE+EIWzoDLGQxN9+nivUZJ4FERQWgWqG2qie/ojyOCxHNgz8nDCyOYUlIO7FIpaX0C++//mv5gGsRpevvlr8TsJ9Srp43Fn9bAcQ==
    SECRET_ACCESS_KEY: AgCauSYlAqpI3GNbTVyQ0OWMrG0MPcQQEq1MgBhqZ2IQYkkLnAcI+9hbl0fR2BvyrUirM3fgplrUSRA6NevzBOvkLC+qsUj5HgFpHw5xehDq0GNsRrMJcEW3vABpYN5oa4Ig2cubrAokqoUBa1SBRPiLrFJxBc6WtwK73dVngKGY4iBXZ/77ApulTuQ7/QxmBTymc5p2QzHe9PeikeZT2wvsVt92hJnQDGbJybEsKhD6cBpGdLeKSGcDQ7Tz3U8OV6lrEh8+nVdUG0O6WBoC6YgnFH1OXw2mrobVtBlaL54+/ZhMVawwM9J16lXnICjKpKFeKWnpWY4u2SkRjx8dv+JcG5J3mo54eYHl6x95erGTxaBmMpNrPK0MfjTY/YIpimJwbmyI6wxmZYN1AzOHdIgnL1DymnuLa2VB3xakeX+noRe+r9mL68Y9OEjDUjCF+DGsMn2fpdn5O3yxN7BRlQc7+aaoxBHm2+DGPt+aP+ecnmX/ejQyTJdp8yNmhgFLaRQD6SmX0ud60OVhMWTGZqKO/JsWvpJTBNYASFAOJ+Fs8eKMsWfPA9UWxhoaZbRqGjOQLnM4OAJ/7sVq7CccNSfQZ0TH0Mx2WW19RDr4B/i5qWkg5BHPbHgtdPL7W+fhJE0vZ6j1XNtG0GWmVmiyaTmdVKmOPGDL6tI7P4u7zBwU6gw7lwcy7DsVqaZ7Q9fbSS1rU/sHhSG+EjnPN3w/0Q7/Emp/ycFujjfS4krX9aXrIBIykJQfu0ASDNmPRqBIX0w2JhjJhiFpE2YcavKs6jmU
  template:
    metadata:
      creationTimestamp: null
      name: r2-backup-creds
      namespace: platform-system
