apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "etalbaas.namespace" . }}
  labels:
    {{- include "etalbaas.labels" . | nindent 4 }}
    kubernetes.io/metadata.name: {{ include "etalbaas.namespace" . }}
