{{- if .Values.operator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: etalbaas-operator-metrics
  namespace: {{ include "etalbaas.namespace" . }}
  labels:
    {{- include "etalbaas.serviceLabels" (dict "root" . "component" "operator") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: operator
    {{- include "etalbaas.selectorLabels" . | nindent 4 }}
{{- end }}
