// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getEventByID = `-- name: GetEventByID :one
SELECT id, project_id, function_id, invocation_id, trigger_type, trigger_data, status, attempt_count, last_error, trace_id, created_at FROM event_history
WHERE id = $1 AND project_id = $2
`

type GetEventByIDParams struct {
	ID        uuid.UUID
	ProjectID string
}

func (q *Queries) GetEventByID(ctx context.Context, arg GetEventByIDParams) (EventHistory, error) {
	row := q.db.QueryRow(ctx, getEventByID, arg.ID, arg.ProjectID)
	var i EventHistory
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FunctionID,
		&i.InvocationID,
		&i.TriggerType,
		&i.TriggerData,
		&i.Status,
		&i.AttemptCount,
		&i.LastError,
		&i.TraceID,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectByIDAndTenantID = `-- name: GetProjectByIDAndTenantID :one
SELECT id, tenant_id, display_name, description, status, postgres_enabled, postgres_extensions, redis_enabled, postgrest_enabled, created_at, updated_at FROM projects
WHERE id = $1 AND tenant_id = $2 AND status != 'deleted'
`

type GetProjectByIDAndTenantIDParams struct {
	ID       string
	TenantID uuid.UUID
}

func (q *Queries) GetProjectByIDAndTenantID(ctx context.Context, arg GetProjectByIDAndTenantIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByIDAndTenantID, arg.ID, arg.TenantID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DisplayName,
		&i.Description,
		&i.Status,
		&i.PostgresEnabled,
		&i.PostgresExtensions,
		&i.RedisEnabled,
		&i.PostgrestEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEventHistoryByFunctionID = `-- name: ListEventHistoryByFunctionID :many
SELECT id, project_id, function_id, invocation_id, trigger_type, trigger_data, status, attempt_count, last_error, trace_id, created_at FROM event_history
WHERE function_id = $1
  AND project_id = $2
  AND ($3::text IS NULL OR status = $3)
  AND ($4::timestamptz IS NULL OR created_at >= $4)
  AND ($5::timestamptz IS NULL OR created_at <= $5)
  AND (
    $6::timestamptz IS NULL
    OR created_at < $6::timestamptz
    OR (created_at = $6::timestamptz AND id < $7)
  )
ORDER BY created_at DESC, id DESC
LIMIT $8
`

type ListEventHistoryByFunctionIDParams struct {
	FunctionID      uuid.UUID
	ProjectID       string
	StatusFilter    *string
	Since           pgtype.Timestamptz
	Until           pgtype.Timestamptz
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	PageSize        int32
}

func (q *Queries) ListEventHistoryByFunctionID(ctx context.Context, arg ListEventHistoryByFunctionIDParams) ([]EventHistory, error) {
	rows, err := q.db.Query(ctx, listEventHistoryByFunctionID,
		arg.FunctionID,
		arg.ProjectID,
		arg.StatusFilter,
		arg.Since,
		arg.Until,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventHistory
	for rows.Next() {
		var i EventHistory
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FunctionID,
			&i.InvocationID,
			&i.TriggerType,
			&i.TriggerData,
			&i.Status,
			&i.AttemptCount,
			&i.LastError,
			&i.TraceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventHistoryByProjectID = `-- name: ListEventHistoryByProjectID :many
SELECT id, project_id, function_id, invocation_id, trigger_type, trigger_data, status, attempt_count, last_error, trace_id, created_at FROM event_history
WHERE project_id = $1
  AND ($2::text IS NULL OR status = $2)
  AND ($3::timestamptz IS NULL OR created_at >= $3)
  AND ($4::timestamptz IS NULL OR created_at <= $4)
  AND (
    $5::timestamptz IS NULL
    OR created_at < $5::timestamptz
    OR (created_at = $5::timestamptz AND id < $6)
  )
ORDER BY created_at DESC, id DESC
LIMIT $7
`

type ListEventHistoryByProjectIDParams struct {
	ProjectID       string
	StatusFilter    *string
	Since           pgtype.Timestamptz
	Until           pgtype.Timestamptz
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	PageSize        int32
}

func (q *Queries) ListEventHistoryByProjectID(ctx context.Context, arg ListEventHistoryByProjectIDParams) ([]EventHistory, error) {
	rows, err := q.db.Query(ctx, listEventHistoryByProjectID,
		arg.ProjectID,
		arg.StatusFilter,
		arg.Since,
		arg.Until,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventHistory
	for rows.Next() {
		var i EventHistory
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FunctionID,
			&i.InvocationID,
			&i.TriggerType,
			&i.TriggerData,
			&i.Status,
			&i.AttemptCount,
			&i.LastError,
			&i.TraceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
