// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	GetEventByID(ctx context.Context, arg GetEventByIDParams) (EventHistory, error)
	GetProjectByIDAndTenantID(ctx context.Context, arg GetProjectByIDAndTenantIDParams) (Project, error)
	ListEventHistoryByFunctionID(ctx context.Context, arg ListEventHistoryByFunctionIDParams) ([]EventHistory, error)
}

var _ Querier = (*Queries)(nil)
