#!/usr/bin/env bash
set -euo pipefail

# EtalBaaS Full Deployment Script
#
# Config files (edit before running):
#   - deploy/post-install/group_vars/all/main.yml        (domain, VIP, S3 — plaintext, committed)
#   - deploy/kubespray/inventory/production/hosts.yaml   (node IPs — gitignored)
#   - deploy/post-install/group_vars/all/vault.yml       (infra secrets — encrypted, gitignored)
#   - deploy/post-install/.vault-password                 (vault password — gitignored)
#   - deploy/scripts/secrets.env                          (K8s secrets — gitignored, sealed after cluster up)
#
# Usage:
#   bash deploy/scripts/deploy.sh [stage]
#
# Stages:
#   cluster    - Provision K8s cluster via kubespray
#   bootstrap  - Post-install (sealed-secrets → ArgoCD → apps → DNS)
#   seal       - Seal K8s secrets (requires running cluster)
#   all        - cluster → bootstrap → seal (default)

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
KUBESPRAY_DIR="$REPO_ROOT/deploy/kubespray"
POST_INSTALL_DIR="$REPO_ROOT/deploy/post-install"
INVENTORY="$KUBESPRAY_DIR/inventory/production/hosts.yaml"
MAIN_VARS="$POST_INSTALL_DIR/group_vars/all/main.yml"
VAULT_FILE="$POST_INSTALL_DIR/group_vars/all/vault.yml"
VAULT_PW_FILE="$POST_INSTALL_DIR/.vault-password"

STAGE="${1:-all}"

# ─── Helpers ─────────────────────────────────────────────────────────────────

log()  { echo "==> $*"; }
err()  { echo "ERROR: $*" >&2; exit 1; }

# Read a top-level key from a plain YAML file.
yaml_val() {
  python3 -c "import yaml,sys; d=yaml.safe_load(open('$1')); print(d.get('$2',''))"
}

# Extract first node IP from hosts.yaml.
first_node_ip() {
  python3 -c "
import yaml
with open('$INVENTORY') as f:
    d = yaml.safe_load(f)
hosts = d['all']['children']['kube_control_plane']['hosts']
print(list(hosts.values())[0]['ansible_host'])
"
}

ssh_var() {
  python3 -c "
import yaml
with open('$INVENTORY') as f:
    d = yaml.safe_load(f)
print(d['all']['vars'].get('$1', '$2'))
"
}

check_prerequisites() {
  command -v ansible-playbook >/dev/null 2>&1 || err "ansible-playbook not found. Install: pip install ansible"
  command -v python3 >/dev/null 2>&1          || err "python3 not found"
  command -v git >/dev/null 2>&1              || err "git not found"
}

validate_config() {
  [[ -f "$INVENTORY" ]]  || err "hosts.yaml not found. Edit deploy/kubespray/inventory/production/hosts.yaml with node IPs."
  [[ -f "$MAIN_VARS" ]]  || err "main.yml not found."
  [[ -f "$VAULT_FILE" ]] || err "vault.yml not found.\n  cp vault.yml.example vault.yml && ansible-vault encrypt vault.yml"
  [[ -f "$VAULT_PW_FILE" ]] || err ".vault-password not found."

  DOMAIN="$(yaml_val "$MAIN_VARS" base_domain)"
  VIP="$(yaml_val "$MAIN_VARS" kube_vip_address)"
  NODE1_IP="$(first_node_ip)"
  SSH_USER="$(ssh_var ansible_user root)"
  SSH_KEY="$(ssh_var ansible_ssh_private_key_file '~/.ssh/id_rsa')"

  [[ "$DOMAIN" != "yourdomain.com" ]] || err "base_domain is still placeholder in main.yml"
  [[ "$VIP" != "203.0.113.100" ]]     || err "kube_vip_address is still placeholder in main.yml"
  [[ "$NODE1_IP" != "203.0.113.10" ]] || err "node IPs are still placeholders in hosts.yaml"
}

# ─── Generate production Helm values from main.yml ───────────────────────────

generate_production_values() {
  local values_file="$REPO_ROOT/deploy/argocd/production/values.yaml"
  local s3_endpoint s3_bucket backup_enabled backup_endpoint backup_bucket

  s3_endpoint="$(yaml_val "$MAIN_VARS" s3_endpoint)"
  s3_bucket="$(yaml_val "$MAIN_VARS" s3_bucket)"
  backup_enabled="$(yaml_val "$MAIN_VARS" backup_enabled)"
  backup_endpoint="$(yaml_val "$MAIN_VARS" backup_endpoint)"
  backup_bucket="$(yaml_val "$MAIN_VARS" backup_bucket)"

  log "Generating production values (domain=$DOMAIN)"

  cat > "$values_file" <<EOF
# Auto-generated by deploy.sh from main.yml. Do not edit manually.
global:
  baseDomain: "$DOMAIN"
  environment: "production"
  imageRegistry: "ghcr.io/kou-etal"

services:
  common:
    replicaCount: 2
  storage:
    s3:
      endpoint: "${s3_endpoint}"
      bucket: "${s3_bucket:-etalbaas-storage}"

certManager:
  issuer:
    email: "admin@$DOMAIN"

metadb:
  internal:
    instances: 3
    storage: 20Gi
    backup:
      enabled: ${backup_enabled:-false}
      endpoint: "${backup_endpoint}"
      bucket: "${backup_bucket:-etalbaas-backups}"
      schedule: "0 2 * * *"
      retentionDays: 30

gotrue:
  externalUrl: "https://auth.$DOMAIN"
  siteUrl: "https://dashboard.$DOMAIN"
EOF
}

# ─── Stage: cluster ──────────────────────────────────────────────────────────

stage_cluster() {
  log "Stage: cluster provisioning"

  if [[ ! -d "$KUBESPRAY_DIR/kubespray" ]]; then
    log "Cloning kubespray v2.25.0..."
    git clone -b v2.25.0 --depth 1 https://github.com/kubernetes-sigs/kubespray.git "$KUBESPRAY_DIR/kubespray"
  else
    log "kubespray already cloned, skipping"
  fi

  log "Installing kubespray Python requirements..."
  pip install -q -r "$KUBESPRAY_DIR/kubespray/requirements.txt"

  # Copy custom group_vars.
  local target_gv="$KUBESPRAY_DIR/inventory/production/group_vars"
  if [[ -d "$KUBESPRAY_DIR/group_vars" ]]; then
    mkdir -p "$target_gv"
    cp -r "$KUBESPRAY_DIR/group_vars/"* "$target_gv/" 2>/dev/null || true
  fi

  log "Running kubespray cluster.yml..."
  cd "$KUBESPRAY_DIR/kubespray"
  ansible-playbook -i "$INVENTORY" cluster.yml --become --become-user=root

  log "Fetching kubeconfig from $NODE1_IP..."
  mkdir -p "$HOME/.kube"
  ssh -i "$SSH_KEY" "${SSH_USER}@${NODE1_IP}" "cat /etc/kubernetes/admin.conf" \
    | sed "s|server: https://127.0.0.1:6443|server: https://${VIP}:6443|" \
    > "$HOME/.kube/config"
  chmod 600 "$HOME/.kube/config"

  log "Cluster provisioning complete."
  kubectl get nodes
}

# ─── Stage: bootstrap ────────────────────────────────────────────────────────

stage_bootstrap() {
  log "Stage: post-install bootstrap"

  kubectl get nodes >/dev/null 2>&1 \
    || err "kubectl cannot reach the cluster. Run 'cluster' stage first."

  generate_production_values

  log "Installing Ansible collections..."
  cd "$POST_INSTALL_DIR"
  ansible-galaxy collection install -r requirements.yml --force

  log "Running bootstrap playbook..."
  ansible-playbook playbooks/bootstrap.yml --vault-password-file="$VAULT_PW_FILE"

  log "Bootstrap complete."
}

# ─── Stage: seal ─────────────────────────────────────────────────────────────

stage_seal() {
  log "Stage: seal K8s secrets"

  kubectl get nodes >/dev/null 2>&1 \
    || err "kubectl cannot reach the cluster."

  command -v kubeseal >/dev/null 2>&1 \
    || err "kubeseal not found. Install: https://github.com/bitnami-labs/sealed-secrets/releases"

  local secrets_env="$SCRIPT_DIR/secrets.env"
  [[ -f "$secrets_env" ]] \
    || err "secrets.env not found.\n  cp secrets.env.example secrets.env  # fill in values"

  log "Running seal-secrets.sh..."
  bash "$SCRIPT_DIR/seal-secrets.sh"

  log "Sealed secrets created. Commit and push:"
  log "  git add deploy/sealed-secrets/ && git commit -m 'chore: seal production secrets' && git push"
}

# ─── Main ────────────────────────────────────────────────────────────────────

check_prerequisites
validate_config

case "$STAGE" in
  cluster)   stage_cluster ;;
  bootstrap) stage_bootstrap ;;
  seal)      stage_seal ;;
  all)
    stage_cluster
    stage_bootstrap
    stage_seal
    log ""
    log "Deployment complete."
    log "  Dashboard:  https://dashboard.${DOMAIN}"
    log "  API:        https://api.${DOMAIN}"
    log ""
    log "Next: git add deploy/sealed-secrets/ && git commit && git push"
    ;;
  *)
    err "Unknown stage: $STAGE. Use: cluster, bootstrap, seal, or all"
    ;;
esac

log "Done."
