// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package metastore

import (
	"context"
)

type Querier interface {
	GetProjectByIDAndTenantID(ctx context.Context, arg GetProjectByIDAndTenantIDParams) (GetProjectByIDAndTenantIDRow, error)
}

var _ Querier = (*Queries)(nil)
