// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package metastore

import (
	"context"

	"github.com/google/uuid"
)

const getProjectByIDAndTenantID = `-- name: GetProjectByIDAndTenantID :one
SELECT id, tenant_id, status
FROM projects
WHERE id = $1 AND tenant_id = $2 AND status != 'deleted'
`

type GetProjectByIDAndTenantIDParams struct {
	ID       string
	TenantID uuid.UUID
}

type GetProjectByIDAndTenantIDRow struct {
	ID       string
	TenantID uuid.UUID
	Status   string
}

func (q *Queries) GetProjectByIDAndTenantID(ctx context.Context, arg GetProjectByIDAndTenantIDParams) (GetProjectByIDAndTenantIDRow, error) {
	row := q.db.QueryRow(ctx, getProjectByIDAndTenantID, arg.ID, arg.TenantID)
	var i GetProjectByIDAndTenantIDRow
	err := row.Scan(&i.ID, &i.TenantID, &i.Status)
	return i, err
}
