// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveProjectsByTenantID = `-- name: CountActiveProjectsByTenantID :one
SELECT COUNT(*) FROM projects
WHERE tenant_id = $1 AND status != 'deleted'
`

func (q *Queries) CountActiveProjectsByTenantID(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveProjectsByTenantID, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO api_keys (
    id, project_id, name, key_hash, key_prefix, role, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, project_id, name, key_hash, key_prefix, role, expires_at, revoked_at, created_at
`

type CreateApiKeyParams struct {
	ID        uuid.UUID
	ProjectID string
	Name      string
	KeyHash   string
	KeyPrefix string
	Role      string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createApiKey,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Role,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Role,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    id, tenant_id, display_name, description,
    postgres_enabled, postgres_extensions, redis_enabled, postgrest_enabled
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, tenant_id, display_name, description, status, postgres_enabled, postgres_extensions, redis_enabled, postgrest_enabled, created_at, updated_at
`

type CreateProjectParams struct {
	ID                 string
	TenantID           uuid.UUID
	DisplayName        string
	Description        *string
	PostgresEnabled    bool
	PostgresExtensions []string
	RedisEnabled       bool
	PostgrestEnabled   bool
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.TenantID,
		arg.DisplayName,
		arg.Description,
		arg.PostgresEnabled,
		arg.PostgresExtensions,
		arg.RedisEnabled,
		arg.PostgrestEnabled,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DisplayName,
		&i.Description,
		&i.Status,
		&i.PostgresEnabled,
		&i.PostgresExtensions,
		&i.RedisEnabled,
		&i.PostgrestEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSecretMetadata = `-- name: CreateSecretMetadata :one
INSERT INTO secrets_metadata (
    id, project_id, name, description
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, project_id, name, description, created_at, updated_at
`

type CreateSecretMetadataParams struct {
	ID          uuid.UUID
	ProjectID   string
	Name        string
	Description string
}

func (q *Queries) CreateSecretMetadata(ctx context.Context, arg CreateSecretMetadataParams) (SecretsMetadatum, error) {
	row := q.db.QueryRow(ctx, createSecretMetadata,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Description,
	)
	var i SecretsMetadatum
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSecretMetadata = `-- name: DeleteSecretMetadata :one
DELETE FROM secrets_metadata
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, name, description, created_at, updated_at
`

type DeleteSecretMetadataParams struct {
	ID        uuid.UUID
	ProjectID string
}

func (q *Queries) DeleteSecretMetadata(ctx context.Context, arg DeleteSecretMetadataParams) (SecretsMetadatum, error) {
	row := q.db.QueryRow(ctx, deleteSecretMetadata, arg.ID, arg.ProjectID)
	var i SecretsMetadatum
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByIDAndTenantID = `-- name: GetProjectByIDAndTenantID :one
SELECT id, tenant_id, display_name, description, status, postgres_enabled, postgres_extensions, redis_enabled, postgrest_enabled, created_at, updated_at FROM projects
WHERE id = $1 AND tenant_id = $2 AND status != 'deleted'
`

type GetProjectByIDAndTenantIDParams struct {
	ID       string
	TenantID uuid.UUID
}

func (q *Queries) GetProjectByIDAndTenantID(ctx context.Context, arg GetProjectByIDAndTenantIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByIDAndTenantID, arg.ID, arg.TenantID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DisplayName,
		&i.Description,
		&i.Status,
		&i.PostgresEnabled,
		&i.PostgresExtensions,
		&i.RedisEnabled,
		&i.PostgrestEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectStatus = `-- name: GetProjectStatus :one
SELECT status FROM projects
WHERE id = $1 AND tenant_id = $2 AND status != 'deleted'
`

type GetProjectStatusParams struct {
	ID       string
	TenantID uuid.UUID
}

func (q *Queries) GetProjectStatus(ctx context.Context, arg GetProjectStatusParams) (string, error) {
	row := q.db.QueryRow(ctx, getProjectStatus, arg.ID, arg.TenantID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getSecretMetadataByID = `-- name: GetSecretMetadataByID :one
SELECT id, project_id, name, description, created_at, updated_at FROM secrets_metadata
WHERE id = $1 AND project_id = $2
`

type GetSecretMetadataByIDParams struct {
	ID        uuid.UUID
	ProjectID string
}

func (q *Queries) GetSecretMetadataByID(ctx context.Context, arg GetSecretMetadataByIDParams) (SecretsMetadatum, error) {
	row := q.db.QueryRow(ctx, getSecretMetadataByID, arg.ID, arg.ProjectID)
	var i SecretsMetadatum
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApiKeysByProjectID = `-- name: ListApiKeysByProjectID :many
SELECT id, project_id, name, key_hash, key_prefix, role, expires_at, revoked_at, created_at FROM api_keys
WHERE project_id = $1
  AND (
    $2 IS NULL
    OR created_at < $2
    OR (created_at = $2 AND id < $3)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListApiKeysByProjectIDParams struct {
	ProjectID       string
	CursorCreatedAt interface{}
	CursorID        pgtype.UUID
	PageSize        int32
}

func (q *Queries) ListApiKeysByProjectID(ctx context.Context, arg ListApiKeysByProjectIDParams) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listApiKeysByProjectID,
		arg.ProjectID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.Role,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByTenantID = `-- name: ListProjectsByTenantID :many
SELECT id, tenant_id, display_name, description, status, postgres_enabled, postgres_extensions, redis_enabled, postgrest_enabled, created_at, updated_at FROM projects
WHERE tenant_id = $1
  AND status != 'deleted'
  AND (
    $2 IS NULL
    OR created_at < $2
    OR (created_at = $2 AND id < $3)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListProjectsByTenantIDParams struct {
	TenantID        uuid.UUID
	CursorCreatedAt interface{}
	CursorID        *string
	PageSize        int32
}

func (q *Queries) ListProjectsByTenantID(ctx context.Context, arg ListProjectsByTenantIDParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByTenantID,
		arg.TenantID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DisplayName,
			&i.Description,
			&i.Status,
			&i.PostgresEnabled,
			&i.PostgresExtensions,
			&i.RedisEnabled,
			&i.PostgrestEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretsByProjectID = `-- name: ListSecretsByProjectID :many
SELECT id, project_id, name, description, created_at, updated_at FROM secrets_metadata
WHERE project_id = $1
  AND (
    $2 IS NULL
    OR created_at < $2
    OR (created_at = $2 AND id < $3)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListSecretsByProjectIDParams struct {
	ProjectID       string
	CursorCreatedAt interface{}
	CursorID        pgtype.UUID
	PageSize        int32
}

func (q *Queries) ListSecretsByProjectID(ctx context.Context, arg ListSecretsByProjectIDParams) ([]SecretsMetadatum, error) {
	rows, err := q.db.Query(ctx, listSecretsByProjectID,
		arg.ProjectID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SecretsMetadatum
	for rows.Next() {
		var i SecretsMetadatum
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeApiKey = `-- name: RevokeApiKey :one
UPDATE api_keys
SET revoked_at = now()
WHERE id = $1 AND project_id = $2 AND revoked_at IS NULL
RETURNING id, project_id, name, key_hash, key_prefix, role, expires_at, revoked_at, created_at
`

type RevokeApiKeyParams struct {
	ID        uuid.UUID
	ProjectID string
}

func (q *Queries) RevokeApiKey(ctx context.Context, arg RevokeApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeApiKey, arg.ID, arg.ProjectID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Role,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateProjectStatus = `-- name: UpdateProjectStatus :one
UPDATE projects
SET status = $3
WHERE id = $1 AND tenant_id = $2 AND status != 'deleted'
RETURNING id, tenant_id, display_name, description, status, postgres_enabled, postgres_extensions, redis_enabled, postgrest_enabled, created_at, updated_at
`

type UpdateProjectStatusParams struct {
	ID       string
	TenantID uuid.UUID
	Status   string
}

func (q *Queries) UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectStatus, arg.ID, arg.TenantID, arg.Status)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DisplayName,
		&i.Description,
		&i.Status,
		&i.PostgresEnabled,
		&i.PostgresExtensions,
		&i.RedisEnabled,
		&i.PostgrestEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSecretMetadataUpdatedAt = `-- name: UpdateSecretMetadataUpdatedAt :one
UPDATE secrets_metadata
SET updated_at = now()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, name, description, created_at, updated_at
`

type UpdateSecretMetadataUpdatedAtParams struct {
	ID        uuid.UUID
	ProjectID string
}

func (q *Queries) UpdateSecretMetadataUpdatedAt(ctx context.Context, arg UpdateSecretMetadataUpdatedAtParams) (SecretsMetadatum, error) {
	row := q.db.QueryRow(ctx, updateSecretMetadataUpdatedAt, arg.ID, arg.ProjectID)
	var i SecretsMetadatum
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
