// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateSecretMetadata(ctx context.Context, arg CreateSecretMetadataParams) (SecretsMetadatum, error)
	DeleteSecretMetadata(ctx context.Context, arg DeleteSecretMetadataParams) (SecretsMetadatum, error)
	GetProjectByIDAndTenantID(ctx context.Context, arg GetProjectByIDAndTenantIDParams) (Project, error)
	GetProjectStatus(ctx context.Context, arg GetProjectStatusParams) (string, error)
	GetSecretMetadataByID(ctx context.Context, arg GetSecretMetadataByIDParams) (SecretsMetadatum, error)
	ListApiKeysByProjectID(ctx context.Context, arg ListApiKeysByProjectIDParams) ([]ApiKey, error)
	ListProjectsByTenantID(ctx context.Context, arg ListProjectsByTenantIDParams) ([]Project, error)
	ListSecretsByProjectID(ctx context.Context, arg ListSecretsByProjectIDParams) ([]SecretsMetadatum, error)
	RevokeApiKey(ctx context.Context, arg RevokeApiKeyParams) (ApiKey, error)
	UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) (Project, error)
	UpdateSecretMetadataUpdatedAt(ctx context.Context, arg UpdateSecretMetadataUpdatedAtParams) (SecretsMetadatum, error)
}

var _ Querier = (*Queries)(nil)
