// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFunction = `-- name: CreateFunction :one
INSERT INTO functions (
    id, project_id, name, display_name, kind, mode,
    source_type, source_config, source_storage_path,
    runtime_preset, runtime_requirements, runtime_dockerfile,
    timeout_sec, gpu_config, triggers, env_vars
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13, $14, $15, $16
)
RETURNING id, project_id, name, display_name, kind, mode, source_type, source_config, source_storage_path, runtime_preset, runtime_requirements, runtime_dockerfile, timeout_sec, gpu_config, triggers, env_vars, status, build_image_ref, build_image_digest, build_duration_sec, last_built_at, created_at, updated_at
`

type CreateFunctionParams struct {
	ID                  uuid.UUID
	ProjectID           string
	Name                string
	DisplayName         string
	Kind                string
	Mode                string
	SourceType          string
	SourceConfig        []byte
	SourceStoragePath   *string
	RuntimePreset       *string
	RuntimeRequirements []string
	RuntimeDockerfile   *string
	TimeoutSec          int32
	GpuConfig           []byte
	Triggers            []byte
	EnvVars             []byte
}

func (q *Queries) CreateFunction(ctx context.Context, arg CreateFunctionParams) (Function, error) {
	row := q.db.QueryRow(ctx, createFunction,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.DisplayName,
		arg.Kind,
		arg.Mode,
		arg.SourceType,
		arg.SourceConfig,
		arg.SourceStoragePath,
		arg.RuntimePreset,
		arg.RuntimeRequirements,
		arg.RuntimeDockerfile,
		arg.TimeoutSec,
		arg.GpuConfig,
		arg.Triggers,
		arg.EnvVars,
	)
	var i Function
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.DisplayName,
		&i.Kind,
		&i.Mode,
		&i.SourceType,
		&i.SourceConfig,
		&i.SourceStoragePath,
		&i.RuntimePreset,
		&i.RuntimeRequirements,
		&i.RuntimeDockerfile,
		&i.TimeoutSec,
		&i.GpuConfig,
		&i.Triggers,
		&i.EnvVars,
		&i.Status,
		&i.BuildImageRef,
		&i.BuildImageDigest,
		&i.BuildDurationSec,
		&i.LastBuiltAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFunction = `-- name: DeleteFunction :one
UPDATE functions
SET status = 'deleted'
WHERE id = $1 AND project_id = $2 AND status != 'deleted'
RETURNING id, project_id, name, display_name, kind, mode, source_type, source_config, source_storage_path, runtime_preset, runtime_requirements, runtime_dockerfile, timeout_sec, gpu_config, triggers, env_vars, status, build_image_ref, build_image_digest, build_duration_sec, last_built_at, created_at, updated_at
`

type DeleteFunctionParams struct {
	ID        uuid.UUID
	ProjectID string
}

func (q *Queries) DeleteFunction(ctx context.Context, arg DeleteFunctionParams) (Function, error) {
	row := q.db.QueryRow(ctx, deleteFunction, arg.ID, arg.ProjectID)
	var i Function
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.DisplayName,
		&i.Kind,
		&i.Mode,
		&i.SourceType,
		&i.SourceConfig,
		&i.SourceStoragePath,
		&i.RuntimePreset,
		&i.RuntimeRequirements,
		&i.RuntimeDockerfile,
		&i.TimeoutSec,
		&i.GpuConfig,
		&i.Triggers,
		&i.EnvVars,
		&i.Status,
		&i.BuildImageRef,
		&i.BuildImageDigest,
		&i.BuildDurationSec,
		&i.LastBuiltAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFunctionByIDAndProjectID = `-- name: GetFunctionByIDAndProjectID :one
SELECT id, project_id, name, display_name, kind, mode, source_type, source_config, source_storage_path, runtime_preset, runtime_requirements, runtime_dockerfile, timeout_sec, gpu_config, triggers, env_vars, status, build_image_ref, build_image_digest, build_duration_sec, last_built_at, created_at, updated_at FROM functions
WHERE id = $1 AND project_id = $2 AND status != 'deleted'
`

type GetFunctionByIDAndProjectIDParams struct {
	ID        uuid.UUID
	ProjectID string
}

func (q *Queries) GetFunctionByIDAndProjectID(ctx context.Context, arg GetFunctionByIDAndProjectIDParams) (Function, error) {
	row := q.db.QueryRow(ctx, getFunctionByIDAndProjectID, arg.ID, arg.ProjectID)
	var i Function
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.DisplayName,
		&i.Kind,
		&i.Mode,
		&i.SourceType,
		&i.SourceConfig,
		&i.SourceStoragePath,
		&i.RuntimePreset,
		&i.RuntimeRequirements,
		&i.RuntimeDockerfile,
		&i.TimeoutSec,
		&i.GpuConfig,
		&i.Triggers,
		&i.EnvVars,
		&i.Status,
		&i.BuildImageRef,
		&i.BuildImageDigest,
		&i.BuildDurationSec,
		&i.LastBuiltAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByIDAndTenantID = `-- name: GetProjectByIDAndTenantID :one
SELECT id, tenant_id, display_name, description, status, postgres_enabled, postgres_extensions, redis_enabled, postgrest_enabled, created_at, updated_at FROM projects
WHERE id = $1 AND tenant_id = $2 AND status != 'deleted'
`

type GetProjectByIDAndTenantIDParams struct {
	ID       string
	TenantID uuid.UUID
}

func (q *Queries) GetProjectByIDAndTenantID(ctx context.Context, arg GetProjectByIDAndTenantIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByIDAndTenantID, arg.ID, arg.TenantID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DisplayName,
		&i.Description,
		&i.Status,
		&i.PostgresEnabled,
		&i.PostgresExtensions,
		&i.RedisEnabled,
		&i.PostgrestEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFunctionsByProjectID = `-- name: ListFunctionsByProjectID :many
SELECT id, project_id, name, display_name, kind, mode, source_type, source_config, source_storage_path, runtime_preset, runtime_requirements, runtime_dockerfile, timeout_sec, gpu_config, triggers, env_vars, status, build_image_ref, build_image_digest, build_duration_sec, last_built_at, created_at, updated_at FROM functions
WHERE project_id = $1
  AND status != 'deleted'
  AND (
    $2 IS NULL
    OR created_at < $2
    OR (created_at = $2 AND id < $3)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListFunctionsByProjectIDParams struct {
	ProjectID       string
	CursorCreatedAt interface{}
	CursorID        pgtype.UUID
	PageSize        int32
}

func (q *Queries) ListFunctionsByProjectID(ctx context.Context, arg ListFunctionsByProjectIDParams) ([]Function, error) {
	rows, err := q.db.Query(ctx, listFunctionsByProjectID,
		arg.ProjectID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Function
	for rows.Next() {
		var i Function
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.DisplayName,
			&i.Kind,
			&i.Mode,
			&i.SourceType,
			&i.SourceConfig,
			&i.SourceStoragePath,
			&i.RuntimePreset,
			&i.RuntimeRequirements,
			&i.RuntimeDockerfile,
			&i.TimeoutSec,
			&i.GpuConfig,
			&i.Triggers,
			&i.EnvVars,
			&i.Status,
			&i.BuildImageRef,
			&i.BuildImageDigest,
			&i.BuildDurationSec,
			&i.LastBuiltAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvocationsByFunctionID = `-- name: ListInvocationsByFunctionID :many
SELECT id, function_id, project_id, trigger_type, mode, status, error_message, duration_ms, gpu_provider, gpu_type, gpu_duration_ms, cold_start_ms, memory_peak_bytes, cpu_millis, retry_count, trace_id, started_at, completed_at, created_at FROM invocations
WHERE function_id = $1
  AND project_id = $2
  AND ($3::text IS NULL OR status = $3)
  AND ($4::timestamptz IS NULL OR created_at >= $4)
  AND ($5::timestamptz IS NULL OR created_at <= $5)
  AND (
    $6 IS NULL
    OR created_at < $6
    OR (created_at = $6 AND id < $7)
  )
ORDER BY created_at DESC, id DESC
LIMIT $8
`

type ListInvocationsByFunctionIDParams struct {
	FunctionID      uuid.UUID
	ProjectID       string
	StatusFilter    *string
	Since           pgtype.Timestamptz
	Until           pgtype.Timestamptz
	CursorCreatedAt interface{}
	CursorID        pgtype.UUID
	PageSize        int32
}

func (q *Queries) ListInvocationsByFunctionID(ctx context.Context, arg ListInvocationsByFunctionIDParams) ([]Invocation, error) {
	rows, err := q.db.Query(ctx, listInvocationsByFunctionID,
		arg.FunctionID,
		arg.ProjectID,
		arg.StatusFilter,
		arg.Since,
		arg.Until,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invocation
	for rows.Next() {
		var i Invocation
		if err := rows.Scan(
			&i.ID,
			&i.FunctionID,
			&i.ProjectID,
			&i.TriggerType,
			&i.Mode,
			&i.Status,
			&i.ErrorMessage,
			&i.DurationMs,
			&i.GpuProvider,
			&i.GpuType,
			&i.GpuDurationMs,
			&i.ColdStartMs,
			&i.MemoryPeakBytes,
			&i.CpuMillis,
			&i.RetryCount,
			&i.TraceID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFunction = `-- name: UpdateFunction :one
UPDATE functions
SET display_name = $3,
    mode = $4,
    source_type = $5,
    source_config = $6,
    source_storage_path = $7,
    runtime_preset = $8,
    runtime_requirements = $9,
    runtime_dockerfile = $10,
    timeout_sec = $11,
    gpu_config = $12,
    triggers = $13,
    env_vars = $14
WHERE id = $1 AND project_id = $2 AND status != 'deleted'
RETURNING id, project_id, name, display_name, kind, mode, source_type, source_config, source_storage_path, runtime_preset, runtime_requirements, runtime_dockerfile, timeout_sec, gpu_config, triggers, env_vars, status, build_image_ref, build_image_digest, build_duration_sec, last_built_at, created_at, updated_at
`

type UpdateFunctionParams struct {
	ID                  uuid.UUID
	ProjectID           string
	DisplayName         string
	Mode                string
	SourceType          string
	SourceConfig        []byte
	SourceStoragePath   *string
	RuntimePreset       *string
	RuntimeRequirements []string
	RuntimeDockerfile   *string
	TimeoutSec          int32
	GpuConfig           []byte
	Triggers            []byte
	EnvVars             []byte
}

func (q *Queries) UpdateFunction(ctx context.Context, arg UpdateFunctionParams) (Function, error) {
	row := q.db.QueryRow(ctx, updateFunction,
		arg.ID,
		arg.ProjectID,
		arg.DisplayName,
		arg.Mode,
		arg.SourceType,
		arg.SourceConfig,
		arg.SourceStoragePath,
		arg.RuntimePreset,
		arg.RuntimeRequirements,
		arg.RuntimeDockerfile,
		arg.TimeoutSec,
		arg.GpuConfig,
		arg.Triggers,
		arg.EnvVars,
	)
	var i Function
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.DisplayName,
		&i.Kind,
		&i.Mode,
		&i.SourceType,
		&i.SourceConfig,
		&i.SourceStoragePath,
		&i.RuntimePreset,
		&i.RuntimeRequirements,
		&i.RuntimeDockerfile,
		&i.TimeoutSec,
		&i.GpuConfig,
		&i.Triggers,
		&i.EnvVars,
		&i.Status,
		&i.BuildImageRef,
		&i.BuildImageDigest,
		&i.BuildDurationSec,
		&i.LastBuiltAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
