// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CreateFunction(ctx context.Context, arg CreateFunctionParams) (Function, error)
	DeleteFunction(ctx context.Context, arg DeleteFunctionParams) (Function, error)
	GetFunctionByIDAndProjectID(ctx context.Context, arg GetFunctionByIDAndProjectIDParams) (Function, error)
	GetProjectByIDAndTenantID(ctx context.Context, arg GetProjectByIDAndTenantIDParams) (Project, error)
	ListFunctionsByProjectID(ctx context.Context, arg ListFunctionsByProjectIDParams) ([]Function, error)
	ListInvocationsByFunctionID(ctx context.Context, arg ListInvocationsByFunctionIDParams) ([]Invocation, error)
	UpdateFunction(ctx context.Context, arg UpdateFunctionParams) (Function, error)
	UpdateFunctionBuildStatus(ctx context.Context, arg UpdateFunctionBuildStatusParams) (Function, error)
}

var _ Querier = (*Queries)(nil)
