// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID        uuid.UUID
	ProjectID string
	Name      string
	KeyHash   string
	KeyPrefix string
	Role      string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt time.Time
}

type EventHistory struct {
	ID           uuid.UUID
	ProjectID    string
	FunctionID   uuid.UUID
	InvocationID pgtype.UUID
	TriggerType  string
	TriggerData  []byte
	Status       string
	AttemptCount int32
	LastError    *string
	TraceID      *string
	CreatedAt    time.Time
}

type Function struct {
	ID                  uuid.UUID
	ProjectID           string
	Name                string
	DisplayName         string
	Kind                string
	Mode                string
	SourceType          string
	SourceConfig        []byte
	SourceStoragePath   *string
	RuntimePreset       *string
	RuntimeRequirements []string
	RuntimeDockerfile   *string
	TimeoutSec          int32
	GpuConfig           []byte
	Triggers            []byte
	EnvVars             []byte
	Status              string
	BuildImageRef       *string
	BuildImageDigest    *string
	BuildDurationSec    pgtype.Int4
	LastBuiltAt         pgtype.Timestamptz
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type Invocation struct {
	ID              uuid.UUID
	FunctionID      uuid.UUID
	ProjectID       string
	TriggerType     string
	Mode            string
	Status          string
	ErrorMessage    *string
	DurationMs      pgtype.Int4
	GpuProvider     *string
	GpuType         *string
	GpuDurationMs   pgtype.Int4
	ColdStartMs     pgtype.Int4
	MemoryPeakBytes pgtype.Int8
	CpuMillis       pgtype.Int8
	RetryCount      int32
	TraceID         *string
	StartedAt       pgtype.Timestamptz
	CompletedAt     pgtype.Timestamptz
	CreatedAt       time.Time
}

type PlatformEvent struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	ProjectID string
	EventType string
	Payload   []byte
	CreatedAt time.Time
}

type Project struct {
	ID                 string
	TenantID           uuid.UUID
	DisplayName        string
	Description        *string
	Status             string
	PostgresEnabled    bool
	PostgresExtensions []string
	RedisEnabled       bool
	PostgrestEnabled   bool
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type SecretsMetadatum struct {
	ID          uuid.UUID
	ProjectID   string
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Tenant struct {
	ID          uuid.UUID
	Email       string
	DisplayName string
	AvatarUrl   *string
	Plan        string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type UsageDaily struct {
	ID                  uuid.UUID
	ProjectID           string
	Date                pgtype.Date
	CpuSeconds          int64
	MemoryMbSeconds     int64
	StorageBytes        int64
	FunctionInvocations int64
	EgressBytes         int64
	DbSizeBytes         int64
	CreatedAt           time.Time
}
