// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error)
	UpdateTenantProfile(ctx context.Context, arg UpdateTenantProfileParams) (Tenant, error)
}

var _ Querier = (*Queries)(nil)
