// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, email, display_name, avatar_url, plan, status, created_at, updated_at
FROM tenants
WHERE id = $1 AND status != 'deleted'
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Plan,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, email, display_name, avatar_url, plan, status, created_at, updated_at
FROM tenants
WHERE status != 'deleted'
  AND (
    $1 IS NULL
    OR created_at < $1
    OR (created_at = $1 AND id < $2)
  )
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListTenantsParams struct {
	CursorCreatedAt interface{}
	CursorID        pgtype.UUID
	PageSize        int32
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants, arg.CursorCreatedAt, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Plan,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenantProfile = `-- name: UpdateTenantProfile :one
UPDATE tenants
SET display_name = COALESCE($2, display_name),
    avatar_url = COALESCE($3, avatar_url),
    updated_at = now()
WHERE id = $1 AND status != 'deleted'
RETURNING id, email, display_name, avatar_url, plan, status, created_at, updated_at
`

type UpdateTenantProfileParams struct {
	ID          uuid.UUID
	DisplayName *string
	AvatarUrl   *string
}

func (q *Queries) UpdateTenantProfile(ctx context.Context, arg UpdateTenantProfileParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantProfile, arg.ID, arg.DisplayName, arg.AvatarUrl)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Plan,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
