BEGIN;

DROP TABLE IF EXISTS secrets_metadata CASCADE;
DROP TABLE IF EXISTS platform_events CASCADE;
DROP TABLE IF EXISTS usage_daily CASCADE;
DROP TABLE IF EXISTS event_history CASCADE;
DROP TABLE IF EXISTS invocations CASCADE;
DROP TABLE IF EXISTS functions CASCADE;
DROP TABLE IF EXISTS api_keys CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS tenants CASCADE;

DROP FUNCTION IF EXISTS update_updated_at();

COMMIT;
