apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: 6.16.6
    helm:
      values: |
        config:
          clients:
            - url: http://loki.monitoring.svc:3100/loki/api/v1/push
          snippets:
            pipelineStages:
              - cri: {}
              - json:
                  expressions:
                    level: level
                    service: service
                    trace_id: trace_id
              - labels:
                  level:
                  service:
                  trace_id:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
