apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-data
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/kou-etal/etalbaas
    targetRevision: HEAD
    path: deploy/sealed-secrets
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
